application:
  port: 8099

mongo:
  username: ""
  password: ""
  port: 27017
  host: "127.0.0.1"
  db: "broward_crab"
  collection: "backend"
  require_auth: false

redis:
  url: "redis://127.0.0.1:6379"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_second: 60
